
> fullstackopen-bloglist-cicd@1.0.0 test
> jest

(node:99852) [MONGOOSE] Warning: Mongoose: looks like you're trying to test a Mongoose app with Jest's default jsdom test environment. Please make sure you read Mongoose's docs on configuring Jest to test Node.js apps: https://mongoosejs.com/docs/jest.html. Set the SUPPRESS_JEST_WARNINGS to true to hide this warning.
(Use `node --trace-warnings ...` to show where the warning was created)
PASS server/tests/dummy.test.js
(node:99849) [MONGOOSE] Warning: Mongoose: looks like you're trying to test a Mongoose app with Jest's default jsdom test environment. Please make sure you read Mongoose's docs on configuring Jest to test Node.js apps: https://mongoosejs.com/docs/jest.html. Set the SUPPRESS_JEST_WARNINGS to true to hide this warning.
(Use `node --trace-warnings ...` to show where the warning was created)
(node:99849) [MONGOOSE] DeprecationWarning: Mongoose: the `strictQuery` option will be switched back to `false` by default in Mongoose 7. Use `mongoose.set('strictQuery', false);` if you want to prepare for this change. Or use `mongoose.set('strictQuery', true);` to suppress this warning.
PASS client/src/components/BlogForm.test.js
FAIL client/src/components/Bloglist.test.js
  ‚óè Console

    console.error
      Error: AggregateError
          at Object.dispatchError (/Users/anton/code/fso-part11-bloglist-with-CI-CD/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:63:19)
          at Request.<anonymous> (/Users/anton/code/fso-part11-bloglist-with-CI-CD/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
          at Request.emit (node:events:530:35)
          at ClientRequest.<anonymous> (/Users/anton/code/fso-part11-bloglist-with-CI-CD/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)
          at ClientRequest.emit (node:events:518:28)
          at emitErrorEvent (node:_http_client:101:11)
          at Socket.socketErrorListener (node:_http_client:504:5)
          at Socket.emit (node:events:518:28)
          at emitErrorNT (node:internal/streams/destroy:169:8)
          at emitErrorCloseNT (node:internal/streams/destroy:128:3)
          at processTicksAndRejections (node:internal/process/task_queues:82:21) {
        type: 'XMLHttpRequest'
      }

      at VirtualConsole.<anonymous> (node_modules/jest-environment-jsdom/build/index.js:63:23)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:66:53)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
      at ClientRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)

    console.error
      Error: AggregateError
          at Object.dispatchError (/Users/anton/code/fso-part11-bloglist-with-CI-CD/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:63:19)
          at Request.<anonymous> (/Users/anton/code/fso-part11-bloglist-with-CI-CD/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
          at Request.emit (node:events:530:35)
          at ClientRequest.<anonymous> (/Users/anton/code/fso-part11-bloglist-with-CI-CD/node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)
          at ClientRequest.emit (node:events:518:28)
          at emitErrorEvent (node:_http_client:101:11)
          at Socket.socketErrorListener (node:_http_client:504:5)
          at Socket.emit (node:events:518:28)
          at emitErrorNT (node:internal/streams/destroy:169:8)
          at emitErrorCloseNT (node:internal/streams/destroy:128:3)
          at processTicksAndRejections (node:internal/process/task_queues:82:21) {
        type: 'XMLHttpRequest'
      }

      at VirtualConsole.<anonymous> (node_modules/jest-environment-jsdom/build/index.js:63:23)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:66:53)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
      at ClientRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)

  ‚óè <Blog /> ‚Ä∫ clicking the like button twice updates the likes

    AxiosError: Network Error

      at XMLHttpRequest.handleError (node_modules/axios/lib/adapters/xhr.js:110:14)
      at XMLHttpRequest.invokeTheCallbackFunction (node_modules/jsdom/lib/jsdom/living/generated/EventHandlerNonNull.js:14:28)
      at XMLHttpRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:35:32)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
      at XMLHttpRequestImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
      at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
      at requestErrorSteps (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:131:3)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:60:3)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
      at ClientRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)
      at Axios.request (node_modules/axios/lib/core/Axios.js:45:41)

  ‚óè <Blog /> ‚Ä∫ clicking the like button twice updates the likes

    AxiosError: Network Error

      at XMLHttpRequest.handleError (node_modules/axios/lib/adapters/xhr.js:110:14)
      at XMLHttpRequest.invokeTheCallbackFunction (node_modules/jsdom/lib/jsdom/living/generated/EventHandlerNonNull.js:14:28)
      at XMLHttpRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:35:32)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:350:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:286:3)
      at XMLHttpRequestImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:233:9)
      at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
      at requestErrorSteps (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:131:3)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:60:3)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
      at ClientRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/http-request.js:121:14)
      at Axios.request (node_modules/axios/lib/core/Axios.js:45:41)

  ‚óè <Blog /> ‚Ä∫ clicking the like button twice updates the likes

    Unable to find an element with the text: likes: 7. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    Ignored nodes: comments, script, style
    [36m<body>[39m
      [36m<div>[39m
        [36m<div[39m
          [33mclass[39m=[32m"blogDiv"[39m
          [33mstyle[39m=[32m"padding-top: 10px; padding-left: 2px; margin-bottom: 5px;"[39m
        [36m>[39m
          [36m<h2>[39m
            [0mGo To Statement Considered Harmful[0m
          [36m</h2>[39m
          [36m<div>[39m
            [0mby [0m
            [0mEdsger W. Dijkstra[0m
          [36m</div>[39m
          [36m<a[39m
            [33mhref[39m=[32m"http://example.com"[39m
          [36m>[39m
            [0mhttp://example.com[0m
          [36m</a>[39m
          [36m<div>[39m
            [0mlikes: [0m
            [0m5[0m
            [36m<button>[39m
              [0mlike[0m
            [36m</button>[39m
          [36m</div>[39m
          [0madded by [0m
          [0mArto Hellas[0m
          [36m<button[39m
            [33mclass[39m=[32m"deleteButton"[39m
          [36m>[39m
            [0mdelete[0m
          [36m</button>[39m
          [36m<h4>[39m
            [0mcomments[0m
          [36m</h4>[39m
          [36m<form>[39m
            [36m<input[39m
              [33mname[39m=[32m"comment"[39m
            [36m/>[39m
            [36m<button[39m
              [33mtype[39m=[32m"submit"[39m
            [36m>[39m
              [0madd[0m
            [36m</button>[39m
          [36m</form>[39m
          [36m<div>[39m
            [0mno comments[0m
          [36m</div>[39m
        [36m</div>[39m
      [36m</div>[39m
    [36m</body>[39m

      48 |     await user.click(likeButton)
      49 |     await user.click(likeButton)
    > 50 |     expect(await screen.findByText('likes: 7')).toBeInTheDocument()
         |                         ^
      51 |   })
      52 | })
      53 |

      at waitForWrapper (node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/wait-for.js:163:27)
      at node_modules/@testing-library/react/node_modules/@testing-library/dom/dist/query-helpers.js:86:33
      at findByText (client/src/components/Bloglist.test.js:50:25)
      at tryCatch (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
      at Generator.<anonymous> (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
      at Generator.next (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)

FAIL server/tests/blog_api.test.js (7.5 s)
  ‚óè Console

    console.log
      Serving static from: /Users/anton/code/fso-part11-bloglist-with-CI-CD/client/dist

      at Object.log (server/app.js:40:9)

  ‚óè deletion of a blog ‚Ä∫ succeeds with status code 204 if id is valid

    expected 204 "No Content", got 401 "Unauthorized"

      117 |     const blogToDelete = blogsAtStart[3]
      118 |
    > 119 |     await api.delete(`/api/blogs/${blogToDelete.id}`).set('Authorization', `Bearer ${token}`).expect(204)
          |                                                                                               ^
      120 |
      121 |     const blogsAtEnd = await helper.blogsInDb()
      122 |     expect(blogsAtEnd).toHaveLength(helper.initialBlogs.length - 1)

      at expect (server/tests/blog_api.test.js:119:95)
      at tryCatch (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
      at Generator.<anonymous> (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
      at Generator.next (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
      ----
      at Test._assertStatus (node_modules/supertest/lib/test.js:252:14)
      at node_modules/supertest/lib/test.js:308:13
      at Test._assertFunction (node_modules/supertest/lib/test.js:285:13)
      at Test.assert (node_modules/supertest/lib/test.js:164:23)
      at Server.localAssert (node_modules/supertest/lib/test.js:120:14)

  ‚óè individual blog update ‚Ä∫ Update likes for a blog post

    TypeError: Cannot read properties of undefined (reading 'id')

      48 |     url: body.url,
      49 |     likes: body.likes,
    > 50 |     user: body.user.id,
         |                     ^
      51 |     comments: body.comments,
      52 |   }
      53 |   const updatedBlog = await Blog.findByIdAndUpdate(request.params.id, blog, { new: true }).populate('user', {

      at id (server/controllers/blogs.js:50:21)
      at tryCatch (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
      at Generator.<anonymous> (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
      at Generator.next (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:7
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:14:12
      at apply (server/controllers/blogs.js:59:2)
      at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
      at next (node_modules/express/lib/router/route.js:149:13)
      at Route.dispatch (node_modules/express/lib/router/route.js:119:3)
      at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
      at node_modules/express/lib/router/index.js:284:15
      at param (node_modules/express/lib/router/index.js:365:14)
      at param (node_modules/express/lib/router/index.js:376:14)
      at Function.process_params (node_modules/express/lib/router/index.js:421:3)
      at next (node_modules/express/lib/router/index.js:280:10)
      at Function.handle (node_modules/express/lib/router/index.js:175:3)
      at router (node_modules/express/lib/router/index.js:47:12)
      at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
      at trim_prefix (node_modules/express/lib/router/index.js:328:13)
      at node_modules/express/lib/router/index.js:286:9
      at Function.process_params (node_modules/express/lib/router/index.js:346:12)
      at next (node_modules/express/lib/router/index.js:280:10)
      at next (server/utils/middleware.js:60:3)
      at tryCatch (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
      at Generator.<anonymous> (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
      at Generator.next (node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:17)
      at _next (node_modules/@babel/runtime/helpers/asyncToGenerator.js:17:9)
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:7
      at node_modules/@babel/runtime/helpers/asyncToGenerator.js:14:12
      at apply (server/utils/middleware.js:43:20)
      at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
      at trim_prefix (node_modules/express/lib/router/index.js:328:13)
      at node_modules/express/lib/router/index.js:286:9
      at Function.process_params (node_modules/express/lib/router/index.js:346:12)
      at next (node_modules/express/lib/router/index.js:280:10)
      at next (server/utils/middleware.js:40:3)
      at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
      at trim_prefix (node_modules/express/lib/router/index.js:328:13)
      at node_modules/express/lib/router/index.js:286:9
      at Function.process_params (node_modules/express/lib/router/index.js:346:12)
      at next (node_modules/express/lib/router/index.js:280:10)
      at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:91:12)
      at trim_prefix (node_modules/express/lib/router/index.js:328:13)
      at node_modules/express/lib/router/index.js:286:9
      at Function.process_params (node_modules/express/lib/router/index.js:346:12)
      at next (node_modules/express/lib/router/index.js:280:10)
      at next (server/utils/middleware.js:10:3)
      at Layer.handle [as handle_request] (node_modules/express/lib/router/layer.js:95:5)
      at trim_prefix (node_modules/express/lib/router/index.js:328:13)
      at node_modules/express/lib/router/index.js:286:9
      at Function.process_params (node_modules/express/lib/router/index.js:346:12)
      at next (node_modules/express/lib/router/index.js:280:10)
      at node_modules/body-parser/lib/read.js:137:5
      at invokeCallback (node_modules/raw-body/index.js:238:16)
      at done (node_modules/raw-body/index.js:227:7)
      at IncomingMessage.onEnd (node_modules/raw-body/index.js:287:7)

  ‚óè individual blog update ‚Ä∫ Update likes for a blog post

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      128 |
      129 | describe('individual blog update', () => {
    > 130 |   test('Update likes for a blog post', async () => {
          |   ^
      131 |     const blogsAtStart = await helper.blogsInDb()
      132 |     const blogToUpdate = blogsAtStart[0]
      133 |     const updatedBlog = { likes: blogToUpdate.likes + 1 }

      at test (server/tests/blog_api.test.js:130:3)
      at Object.describe (server/tests/blog_api.test.js:129:1)

A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
Test Suites: 2 failed, 2 passed, 4 total
Tests:       3 failed, 17 passed, 20 total
Snapshots:   0 total
Time:        8.275 s
Ran all test suites.
